In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report

In [86]:
df = pd.read_csv('basic_cleaned_exoplanets.csv')
df.head()

Unnamed: 0     kepid kepoi_name  koi_disposition  koi_pdisposition  \
0           0  10797460  K00752.01                1                 1   
1           1  10797460  K00752.02                1                 1   
2           2  10811496  K00753.01                0                 1   
3           3  10848459  K00754.01               -1                -1   
4           4  10854555  K00755.01                1                 1   

   koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  ...  \
0      1.000              0              0              0              0  ...   
1      0.969              0              0              0              0  ...   
2      0.000              0              0              0              0  ...   
3      0.000              0              1              0              0  ...   
4      1.000              0              0              0              0  ...   

   koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  koi_srad  \
0           -81.0      4.467           0.064          -0.096     0.927   
1           -81.0      4.467           0.064          -0.096     0.927   
2          -176.0      4.544           0.044          -0.176     0.868   
3          -174.0      4.564           0.053          -0.168     0.791   
4          -211.0      4.438           0.070          -0.210     1.046   

   koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag  
0          0.105         -0.061  291.93423  48.141651      15.347  
1          0.105         -0.061  291.93423  48.141651      15.347  
2          0.233         -0.078  297.00482  48.134129      15.436  
3          0.201         -0.067  285.53461  48.285210      15.597  
4          0.334         -0.133  288.75488  48.226200      15.509  

[5 rows x 47 columns]

In [87]:
import seaborn as sns


In [88]:
corrs = df.corrwith(df["koi_disposition"])

In [89]:
corr_features = list(corrs.keys())
corr_features.sort(key=lambda x: abs(corrs[x]),reverse=True)
corr_features

['koi_disposition',
 'koi_pdisposition',
 'koi_score',
 'koi_fpflag_ss',
 'Unnamed: 0',
 'koi_fpflag_co',
 'koi_steff_err1',
 'koi_fpflag_ec',
 'koi_steff_err2',
 'koi_teq',
 'koi_fpflag_nt',
 'koi_depth',
 'koi_slogg_err2',
 'koi_model_snr',
 'koi_tce_plnt_num',
 'koi_impact',
 'koi_steff',
 'ra',
 'koi_slogg_err1',
 'koi_slogg',
 'koi_depth_err1',
 'koi_depth_err2',
 'koi_duration',
 'koi_impact_err1',
 'koi_srad_err1',
 'koi_duration_err1',
 'koi_duration_err2',
 'dec',
 'kepid',
 'koi_srad_err2',
 'koi_srad',
 'koi_period_err1',
 'koi_period_err2',
 'koi_prad',
 'koi_impact_err2',
 'koi_time0bk_err1',
 'koi_time0bk_err2',
 'koi_insol_err1',
 'koi_prad_err1',
 'koi_prad_err2',
 'koi_period',
 'koi_kepmag',
 'koi_insol',
 'koi_insol_err2',
 'koi_time0bk']

In [90]:
for j,i in enumerate(corr_features):
    print(i,corrs[i])
    if j >= 25:
        break

koi_disposition 1.0
koi_pdisposition 0.9076514887734979
koi_score 0.868456240130021
koi_fpflag_ss -0.561378542055164
Unnamed: 0 -0.5177623550184368
koi_fpflag_co -0.5016258012397037
koi_steff_err1 -0.40130468883321674
koi_fpflag_ec -0.3729827387972996
koi_steff_err2 0.35866157939296095
koi_teq -0.3236837397819546
koi_fpflag_nt -0.31423369718646693
koi_depth -0.27968450859585403
koi_slogg_err2 0.26564246967571314
koi_model_snr -0.2506092505507908
koi_tce_plnt_num 0.24891369131514232
koi_impact -0.22563388410999238
koi_steff -0.20660437558531786
ra -0.1766835322330056
koi_slogg_err1 -0.17385773881468577
koi_slogg 0.1685015986319295
koi_depth_err1 -0.14679571153186033
koi_depth_err2 0.14679571153186033
koi_duration -0.14642634789610262
koi_impact_err1 -0.1391866476736448
koi_srad_err1 -0.13233891336777792
koi_duration_err1 -0.11451079193814473


In [91]:
df1 = df[corr_features[:23]]
df1 = df1.drop(columns=['Unnamed: 0','koi_disposition'])
df1.head()

koi_pdisposition  koi_score  koi_fpflag_ss  koi_fpflag_co  koi_steff_err1  \
0                 1      1.000              0              0            81.0   
1                 1      0.969              0              0            81.0   
2                 1      0.000              0              0           158.0   
3                -1      0.000              1              0           157.0   
4                 1      1.000              0              0           169.0   

   koi_fpflag_ec  koi_steff_err2  koi_teq  koi_fpflag_nt  koi_depth  ...  \
0              0           -81.0    793.0              0      616.0  ...   
1              0           -81.0    443.0              0      875.0  ...   
2              0          -176.0    638.0              0    10800.0  ...   
3              0          -174.0   1395.0              0     8080.0  ...   
4              0          -211.0   1406.0              0      603.0  ...   

   koi_model_snr  koi_tce_plnt_num  koi_impact  koi_steff         ra  \
0           35.8               1.0       0.146     5455.0  291.93423   
1           25.8               2.0       0.586     5455.0  291.93423   
2           76.3               1.0       0.969     5853.0  297.00482   
3          505.6               1.0       1.276     5805.0  285.53461   
4           40.9               1.0       0.701     6031.0  288.75488   

   koi_slogg_err1  koi_slogg  koi_depth_err1  koi_depth_err2  koi_duration  
0           0.064      4.467            19.5           -19.5       2.95750  
1           0.064      4.467            35.5           -35.5       4.50700  
2           0.044      4.544           171.0          -171.0       1.78220  
3           0.053      4.564            12.8           -12.8       2.40641  
4           0.070      4.438            16.9           -16.9       1.65450  

[5 rows x 21 columns]

In [92]:
columns_to_normalize = df1.drop(columns=["koi_pdisposition","koi_fpflag_ss","koi_fpflag_co","koi_fpflag_ec","koi_fpflag_nt",]).columns
df1[columns_to_normalize] = (df1[columns_to_normalize]-df1[columns_to_normalize].min())/(df1[columns_to_normalize].max()-df1[columns_to_normalize].min())
df1.head()

koi_pdisposition  koi_score  koi_fpflag_ss  koi_fpflag_co  koi_steff_err1  \
0                 1      1.000              0              0        0.119822   
1                 1      0.969              0              0        0.119822   
2                 1      0.000              0              0        0.233728   
3                -1      0.000              1              0        0.232249   
4                 1      1.000              0              0        0.250000   

   koi_fpflag_ec  koi_steff_err2   koi_teq  koi_fpflag_nt  koi_depth  ...  \
0              0        0.954030  0.048096              0   0.000663  ...   
1              0        0.954030  0.024082              0   0.000944  ...   
2              0        0.900114  0.037461              0   0.011709  ...   
3              0        0.901249  0.089400              0   0.008759  ...   
4              0        0.880250  0.090154              0   0.000649  ...   

   koi_model_snr  koi_tce_plnt_num  koi_impact  koi_steff        ra  \
0       0.003690          0.000000    0.005788   0.211107  0.552405   
1       0.002585          0.142857    0.023232   0.211107  0.552405   
2       0.008164          0.000000    0.038416   0.241179  0.784312   
3       0.055588          0.000000    0.050587   0.237552  0.259712   
4       0.004253          0.000000    0.027791   0.254628  0.406994   

   koi_slogg_err1  koi_slogg  koi_depth_err1  koi_depth_err2  koi_duration  
0        0.043478   0.831296        0.001423        0.998577      0.019204  
1        0.043478   0.831296        0.002591        0.997409      0.030413  
2        0.029891   0.845778        0.012482        0.987518      0.010702  
3        0.036005   0.849539        0.000934        0.999066      0.015217  
4        0.047554   0.825842        0.001234        0.998766      0.009778  

[5 rows x 21 columns]

In [93]:
X = df1.drop(columns=["koi_pdisposition"])
y = df1["koi_pdisposition"]

In [94]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y)

In [95]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [96]:
nb_model = MultinomialNB()
nb_model.fit(X_train,y_train)

MultinomialNB()

In [97]:
nb_model.score(X_test,y_test)

1.0

In [98]:
y_predicted = nb_model.predict(X_test)
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00       748
           1       1.00      1.00      1.00       813

    accuracy                           1.00      1561
   macro avg       1.00      1.00      1.00      1561
weighted avg       1.00      1.00      1.00      1561



In [99]:
unique, counts = np.unique(y_predicted, return_counts=True)
print(unique,counts)

[-1  1] [748 813]


In [100]:
knn_model = KNeighborsClassifier()
knn_model.fit(X_train,y_train)

KNeighborsClassifier()

In [101]:
knn_model.score(X_test,y_test)

1.0

In [102]:
y_predicted = knn_model.predict(X_test)
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00       748
           1       1.00      1.00      1.00       813

    accuracy                           1.00      1561
   macro avg       1.00      1.00      1.00      1561
weighted avg       1.00      1.00      1.00      1561



In [103]:
forest_model = RandomForestClassifier(n_estimators=100)
forest_model.fit(X_train,y_train)

RandomForestClassifier()

In [104]:
forest_model.score(X_test,y_test)

0.9955156950672646

In [105]:
y_predicted = forest_model.predict(X_test)
print(classification_report(y_test, y_predicted))

              precision    recall  f1-score   support

          -1       0.99      1.00      1.00       748
           1       1.00      0.99      1.00       813

    accuracy                           1.00      1561
   macro avg       1.00      1.00      1.00      1561
weighted avg       1.00      1.00      1.00      1561



In [106]:
logi_model = LogisticRegression()
logi_model.fit(X_train,y_train)

LogisticRegression()

In [107]:
logi_model.score(X_test,y_test)

1.0

In [108]:
kmeans_model = KMeans(n_clusters=2)
kmeans_model.fit(X_train)

KMeans(n_clusters=2)

In [109]:
kmeans_model.score(X_test)

-860.4117933112559

In [110]:
predicted = kmeans_model.predict(X_test)
predicted[:10]

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [111]:
actual = np.array(y_test)
actual[:10]

array([ 1, -1, -1,  1,  1,  1,  1,  1,  1,  1], dtype=int64)

In [112]:
for i in range(len(actual)):
    if actual[i] == -1:
        actual[i] = 1
    else:
        actual[i] = 0
predicted[:10]

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [113]:
from sklearn import metrics

results = metrics.accuracy_score(actual, predicted)
results

0.9660474055092889

In [114]:
print(classification_report(actual, predicted))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       813
           1       0.95      0.98      0.97       748

    accuracy                           0.97      1561
   macro avg       0.97      0.97      0.97      1561
weighted avg       0.97      0.97      0.97      1561



In [115]:
import tensorflow as tf
from tensorflow.keras import models,Sequential
from tensorflow.keras.layers import Dense

In [116]:
def getANNModel(input_dim):
    model = Sequential()
    model.add(Dense(64, input_shape=(input_dim,), activation='relu'))
    model.add(Dense(64, activation = 'relu'))
    model.add(Dense(1, activation = 'sigmoid'))
    model.compile(optimizer='adam',loss="binary_crossentropy",metrics=['accuracy'])
    return model

In [117]:
y_train = np.array(y_train)
y_test = np.array(y_test)
y_train[y_train == -1] = 0
y_test[y_test == -1] = 0

In [118]:
X_train.shape

(6241, 20)

In [119]:
model = getANNModel(X_train.shape[1])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 64)                1344      
                                                                 
 dense_7 (Dense)             (None, 64)                4160      
                                                                 
 dense_8 (Dense)             (None, 1)                 65        
                                                                 
Total params: 5569 (21.75 KB)
Trainable params: 5569 (21.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [120]:
model.fit(X_train,y_train,epochs=20)

Epoch 1/20


196/196 [==============================] - 2s 3ms/step - loss: 0.1346 - accuracy: 0.9756
Epoch 2/20
196/196 [==============================] - 1s 3ms/step - loss: 0.0114 - accuracy: 0.9979
Epoch 3/20
196/196 [==============================] - 1s 3ms/step - loss: 0.0079 - accuracy: 0.9981
Epoch 4/20
196/196 [==============================] - 1s 3ms/step - loss: 0.0071 - accuracy: 0.9981
Epoch 5/20
196/196 [==============================] - 1s 4ms/step - loss: 0.0068 - accuracy: 0.9982
Epoch 6/20
196/196 [==============================] - 1s 3ms/step - loss: 0.0058 - accuracy: 0.9979
Epoch 7/20
196/196 [==============================] - 1s 4ms/step - loss: 0.0066 - accuracy: 0.9981
Epoch 8/20
196/196 [==============================] - 1s 4ms/step - loss: 0.0062 - accuracy: 0.9979
Epoch 9/20
196/196 [==============================] - 1s 4ms/step - loss: 0.0048 - accuracy: 0.9987
Epoch 10/20
196/196 [==============================] - 1s 3ms/step - loss: 0.0061 - accuracy: 0.9979
Epoch 11/2

In [121]:
model.evaluate(X_test,y_test)

49/49 [==============================] - 0s 4ms/step - loss: 3.0573e-04 - accuracy: 1.0000


[0.00030573178082704544, 1.0]